services:
  hw-backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres
    environment:
      SERVER_PORT: ${SERVER_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
      RUST_LOG: ${RUST_LOG}
      LOG_FILE: ${LOG_FILE}
      AUTH_ENABLED: ${AUTH_ENABLED}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@web-db:${DB_PORT}/${DB_NAME}

  # hw-frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  #   depends_on:
  #     - hw-backend
    

  postgres:
    container_name: web-db
    image: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
      restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
