services:
  hw-frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      VITE_API_URL: ${API_URL}
    restart: unless-stopped
    networks:
      - postgres_database

  hw-backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
      RUST_LOG: ${RUST_LOG}
      LOG_FILE: ${LOG_FILE}
      AUTH_ENABLED: ${AUTH_ENABLED}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}
      FRONTEND_PORT: ${FRONTEND_PORT}
    volumes:
      - backend-logs:/logs
    restart: unless-stopped
    networks:
      - postgres_database

volumes:
  postgres-data:
  backend-logs:

networks:
  postgres_database:
    external: true
