// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::db::schema::posts;
use crate::db::schema::tags;
use crate::db::schema::users;
use chrono::offset::Utc;
use chrono::NaiveDateTime;
use serde::{Deserialize, Serialize};

#[derive(Queryable, Debug, Serialize, Deserialize, AsChangeset)]
#[diesel(table_name = posts)]
pub struct Post {
    pub slug: String,
    pub title: String,
    pub body: String,
    pub author_id: i32,
    pub is_published: bool,
    pub created_at: NaiveDateTime,
    pub updated_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug, Serialize, Deserialize, AsChangeset)]
pub struct Tag {
    pub slug: String,
    pub name: String,
    pub background_color: Option<String>,
    pub foreground_color: Option<String>,
}

#[derive(Queryable, Debug, Serialize, Deserialize)]
pub struct TagsToPost {
    pub id: i32,
    pub post_id: i32,
    pub tag_id: i32,
}

#[derive(Queryable, Debug, Serialize, Deserialize, AsChangeset)]
pub struct User {
    pub id: i32,
    pub name: String,
    pub password: String,
    pub email: Option<String>,
    pub is_staff: bool,
}
