// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use crate::db::schema::users;
use crate::db::schema::posts;
use crate::db::schema::tags;
use chrono::DateTime;
use chrono::offset::Utc;
use serde::{Serialize, Deserialize};

#[derive(Queryable, Debug, Serialize, Deserialize, AsChangeset)]
pub struct Post {
    pub id: i32,
    pub title: String,
    pub body: String,
    pub author_id: i32,
    pub is_published: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: Option<DateTime<Utc>>,
}

#[derive(Queryable, Debug, Serialize, Deserialize, AsChangeset)]
pub struct Tag {
    pub id: i32,
    pub name: String,
    pub background_color: Option<String>,
    pub foreground_color: Option<String>,
}

#[derive(Queryable, Debug, Serialize, Deserialize)]
pub struct TagsToPost {
    pub id: i32,
    pub post_id: i32,
    pub tag_id: i32,
}

#[derive(Queryable, Debug, Serialize, Deserialize, AsChangeset)]
// #[table_name = "users"]
pub struct User {
    pub id: i32,
    pub name: String,
    pub password: String,
    pub email: Option<String>,
    pub is_staff: bool,
}

